/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ParkCreditInterface extends Interface {
    getFunction(nameOrSignature: "PARK_CREDIT" | "balanceOf" | "balanceOfBatch" | "burners" | "isApprovedForAll" | "minters" | "owner" | "renounceOwnership" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setBurner" | "setMinter" | "supportsInterface" | "transferOwnership" | "uri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "BurnerUpdated" | "CreditsBurned" | "CreditsMinted" | "MinterUpdated" | "OwnershipTransferred" | "TransferBatch" | "TransferSingle" | "URI"): EventFragment;

    encodeFunctionData(functionFragment: 'PARK_CREDIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'burners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'minters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setBurner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMinter', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'PARK_CREDIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBurner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BurnerUpdatedEvent {
      export type InputTuple = [account: AddressLike, status: boolean];
      export type OutputTuple = [account: string, status: boolean];
      export interface OutputObject {account: string, status: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditsBurnedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditsMintedEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinterUpdatedEvent {
      export type InputTuple = [account: AddressLike, status: boolean];
      export type OutputTuple = [account: string, status: boolean];
      export interface OutputObject {account: string, status: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ParkCredit extends BaseContract {
    
    connect(runner?: ContractRunner | null): ParkCredit;
    waitForDeployment(): Promise<this>;

    interface: ParkCreditInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PARK_CREDIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    burners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setBurner: TypedContractMethod<
      [account: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMinter: TypedContractMethod<
      [account: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PARK_CREDIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'burners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBurner'): TypedContractMethod<
      [account: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinter'): TypedContractMethod<
      [account: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BurnerUpdated'): TypedContractEvent<BurnerUpdatedEvent.InputTuple, BurnerUpdatedEvent.OutputTuple, BurnerUpdatedEvent.OutputObject>;
getEvent(key: 'CreditsBurned'): TypedContractEvent<CreditsBurnedEvent.InputTuple, CreditsBurnedEvent.OutputTuple, CreditsBurnedEvent.OutputObject>;
getEvent(key: 'CreditsMinted'): TypedContractEvent<CreditsMintedEvent.InputTuple, CreditsMintedEvent.OutputTuple, CreditsMintedEvent.OutputObject>;
getEvent(key: 'MinterUpdated'): TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BurnerUpdated(address,bool)': TypedContractEvent<BurnerUpdatedEvent.InputTuple, BurnerUpdatedEvent.OutputTuple, BurnerUpdatedEvent.OutputObject>;
      BurnerUpdated: TypedContractEvent<BurnerUpdatedEvent.InputTuple, BurnerUpdatedEvent.OutputTuple, BurnerUpdatedEvent.OutputObject>;
    

      'CreditsBurned(address,uint256)': TypedContractEvent<CreditsBurnedEvent.InputTuple, CreditsBurnedEvent.OutputTuple, CreditsBurnedEvent.OutputObject>;
      CreditsBurned: TypedContractEvent<CreditsBurnedEvent.InputTuple, CreditsBurnedEvent.OutputTuple, CreditsBurnedEvent.OutputObject>;
    

      'CreditsMinted(address,uint256)': TypedContractEvent<CreditsMintedEvent.InputTuple, CreditsMintedEvent.OutputTuple, CreditsMintedEvent.OutputObject>;
      CreditsMinted: TypedContractEvent<CreditsMintedEvent.InputTuple, CreditsMintedEvent.OutputTuple, CreditsMintedEvent.OutputObject>;
    

      'MinterUpdated(address,bool)': TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
      MinterUpdated: TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    
    };
  }