[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["../node_modules"]
remappings = ["@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"]

[fmt]
line_length = 100