export const parkChainRouterAbi = [
  {
    type: "function",
    name: "PARK_CREDIT",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "MEMBERSHIP_MANAGER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "OPERATOR_REGISTRY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "OPERATOR_TREASURY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "PARKING_LEDGER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getContract",
    stateMutability: "view",
    inputs: [{ name: "key", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

export const parkCreditAbi = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "id", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const membershipManagerAbi = [
  {
    type: "function",
    name: "setTier",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierId", type: "uint256" },
      { name: "name", type: "string" },
      { name: "monthlyCredits", type: "uint256" },
      { name: "priceWei", type: "uint256" },
      { name: "monthlyHourCap", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "purchaseMembership",
    stateMutability: "payable",
    inputs: [{ name: "tierId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "renewMembership",
    stateMutability: "payable",
    inputs: [{ name: "tierId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "isMemberActive",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getMemberTier",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMemberMonthlyHourCap",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMembershipExpiry",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const operatorRegistryAbi = [
  {
    type: "function",
    name: "STANDARD_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "DISABLED_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "EV_CHARGING_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "MOTORBIKE_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "FAMILY_SLOT_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "WOMEN_SLOT_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "registerOperator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "wallet", type: "address" },
      { name: "name", type: "string" },
      { name: "categories", type: "bytes32[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeOperator",
    stateMutability: "nonpayable",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSupportedCategory",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "category", type: "bytes32" },
      { name: "supported", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setPricePerHour",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "category", type: "bytes32" },
      { name: "price", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setNoShowFee",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "fee", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isWhitelisted",
    stateMutability: "view",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "supportsCategory",
    stateMutability: "view",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "category", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getPricePerHour",
    stateMutability: "view",
    inputs: [
      { name: "operatorId", type: "uint256" },
      { name: "category", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getNoShowFee",
    stateMutability: "view",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getOperatorWallet",
    stateMutability: "view",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

export const parkingLedgerAbi = [
  {
    type: "function",
    name: "STANDARD_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "DISABLED_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "EV_CHARGING_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "MOTORBIKE_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "FAMILY_SLOT_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "WOMEN_SLOT_CATEGORY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "setGracePeriodMinutes",
    stateMutability: "nonpayable",
    inputs: [{ name: "minutes_", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setGracePeriod",
    stateMutability: "nonpayable",
    inputs: [{ name: "minutes_", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "reserve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operatorID", type: "uint256" },
      { name: "category", type: "bytes32" },
      { name: "startTime", type: "uint256" },
      { name: "duration", type: "uint256" },
    ],
    outputs: [{ name: "reservationID", type: "uint256" }],
  },
  {
    type: "function",
    name: "cancelReservation",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationID", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "checkIn",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationID", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "checkOut",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationID", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "markNoShow",
    stateMutability: "nonpayable",
    inputs: [{ name: "reservationID", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getMemberReservations",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getActiveReservation",
    stateMutability: "view",
    inputs: [{ name: "member", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getReservation",
    stateMutability: "view",
    inputs: [{ name: "reservationID", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "reservationID", type: "uint256" },
          { name: "member", type: "address" },
          { name: "operatorID", type: "uint256" },
          { name: "category", type: "bytes32" },
          { name: "startTime", type: "uint256" },
          { name: "duration", type: "uint256" },
          { name: "checkInTime", type: "uint256" },
          { name: "status", type: "uint8" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getUsedHoursByCategory",
    stateMutability: "view",
    inputs: [
      { name: "member", type: "address" },
      { name: "category", type: "bytes32" },
      { name: "monthKey", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUsedHoursByOperator",
    stateMutability: "view",
    inputs: [
      { name: "member", type: "address" },
      { name: "operatorID", type: "uint256" },
      { name: "monthKey", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMonthKey",
    stateMutability: "pure",
    inputs: [{ name: "timestamp", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const operatorTreasuryAbi = [
  {
    type: "function",
    name: "setAllocator",
    stateMutability: "nonpayable",
    inputs: [{ name: "newAllocator", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCreditToEthRate",
    stateMutability: "nonpayable",
    inputs: [{ name: "weiPerCredit", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getAccumulatedEarnings",
    stateMutability: "view",
    inputs: [{ name: "operatorId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getCreditToEthRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
